doctrine:
    dbal:
        driver: 'pdo_mysql'
        host: '%env(DATABASE_HOST)%'          # Récupère l'hôte de la base de données
        port: '%env(DATABASE_PORT)%'          # Récupère le port de la base de données
        dbname: '%env(DATABASE_NAME)%'        # Récupère le nom de la base de données
        user: '%env(DATABASE_USER)%'          # Récupère l'utilisateur de la base de données
        password: '%env(DATABASE_PASSWORD)%'  # Récupère le mot de passe de la base de données
        charset: UTF8

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

options:
!php/const PDO::MYSQL_ATTR_SSL_CA: '/usr/share/ca-certificates/Scalingo/scalingo-database.pem'
!php/const PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: true