framework:
    secret: '%env(APP_SECRET)%'

    # Configuration des proxies de confiance
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: 
        - 'x-forwarded-for'
        - 'x-forwarded-host'
        - 'x-forwarded-port'
        - 'x-forwarded-proto'
        - 'x-forwarded-prefix'

    profiler: 
        only_exceptions: false

    session: 
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 0
        gc_probability: 1
        gc_divisor: 1000
        gc_maxlifetime: 1440
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        metadata_update_threshold: 0
        sid_bits_per_character: 4

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file