security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:  # 🔥 Cette clé est obligatoire pour déclarer les firewalls !
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/  # 🔥 Assure que ce firewall capture toutes les routes
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\SecurityAuthenticator
            entry_point: App\Security\SecurityAuthenticator

            logout:
                path: app_logout
                target: app_login  # 🔥 Redirige après déconnexion

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

            form_login:  # 🔥 Ajouté pour permettre la connexion via formulaire
                login_path: app_login
                check_path: app_login
                default_target_path: app_home

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/formation, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
