security:
  # Les fournisseurs de données utilisateur
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    main:
      pattern: ^/
      # Si tu veux une authentification avec formulaire
      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: email
        password_parameter: password
        always_use_default_target_path: true
        default_target_path: /dashboard  # Page vers laquelle rediriger après une connexion réussie
      # Configuration pour 'remember me'
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800  # 1 semaine
        path: /
      # Log out redirection
      logout:
        path: app_logout
        target: /

  access_control:
    # Définir qui peut accéder à quelle page
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
